---
jobs:
- name: api-gateway
  serial: true
  plan:
  - get: master
  - task: maven-build
    file: master/api-gateway/ci/tasks/mvn_build.yml
  - put: pcf
    params:
        manifest: master/api-gateway/ci/manifests/manifest.yml       
resources:
- name: master
  type: git
  source:
    uri:  ((github-url))
    branch:  master
    username: ((github-username))
    password: ((github-password))
- name: pcf
  type: cf
  source:
    api:  ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))