spring:
  application:
    name: api-gateway
server:
  port: 9500
zuul:
  routes:
    bank-service:
      path: /bankms/**
      url: ${bank.service.url}
      strip-prefix: true
    user-service:
      path: /userms/**
      url: ${user.service.url}
      strip-prefix: true
  retryable: true

logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul:
              web: debug



