apiVersion: apps/v1
kind: Deployment
metadata:
  name: fork-join-deployment
spec:
  selector:
    matchLabels:
      app: bank-service
  replicas: 2
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: bank-service
        ports:
        - containerPort: 9001