platform: linux
image_resource:
  type: docker-image
  source:
   repository: node
inputs:
  - name: master
outputs:
  - name: artifacts
run:
  path: sh
  args:
            - -exec
            - |
                cd master/fork-join-demo
                npm install
                npm run build
                ls
                cp -R dist ../artifacts/  
                pwd