apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: {{ include "fork-join-chart.name" . }}    
    release: {{ .Release.Name }}
    env: {{ .Values.environment }}
    chart-name: {{ include "fork-join-chart.chart" . }}
spec:
  replicas: {{ .Values.apigateway.replicas }}
  selector:
    matchLabels:
      app: {{ include "fork-join-chart.name" . }}
      release: {{ .Release.Name }}     
  template:
    metadata:
      labels:
        app: {{ include "fork-join-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.apigateway.image.name }}
          image: "{{ .Values.apigateway.image.repository }}:{{ .Values.apigateway.image.tag }}"
          imagePullPolicy: {{ .Values.apigateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9500
              protocol: TCP
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
                configMapKeyRef:
                    name: spring-config-map
                    key: spring.profiles.active
          - name: user.service.url
            valueFrom:
                configMapKeyRef:
                    name: api-gateway-config-map
                    key: user.service.url
          - name: bank.service.url
            valueFrom:
                configMapKeyRef:
                    name: api-gateway-config-map
                    key: bank.service.url
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
