apiVersion: apps/v1
kind: Deployment
metadata:
  name: fork-join-demo-ui
  labels:
    app: {{ include "fork-join-chart.name" . }}    
    release: {{ .Release.Name }}
    env: {{ .Values.environment }}
    chart-name: {{ include "fork-join-chart.chart" . }}
spec:
  replicas: {{ .Values.forkjoinangular.replicas }}
  selector:
    matchLabels:
      app: {{ include "fork-join-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "fork-join-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.forkjoinangular.image.name }}
          image: "{{ .Values.forkjoinangular.image.repository }}:{{ .Values.forkjoinangular.image.tag }}"
          imagePullPolicy: {{ .Values.forkjoinangular.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
