apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: {{ include "fork-join-chart.name" . }}
    chart-name: {{ include "fork-join-chart.chart" . }}
    release: {{ .Release.Name }}   
spec:
  type: {{ .Values.userservice.service.type }}
  ports:
    - port: {{ .Values.userservice.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "fork-join-chart.name" . }}
    chart-name: {{ include "fork-join-chart.chart" . }}
    release: {{ .Release.Name }}   
