
# config map to pass environment variables to containers
apiVersion: v1
data:
  spring.profiles.active: k8s
kind: ConfigMap
metadata:
  name: spring-config-map

---
# config map to pass environment variables to containers
apiVersion: v1
data:
  user.service.url: http://${USER_SERVICE_SERVICE_HOST}:${USER_SERVICE_SERVICE_PORT}
  bank.service.url: http://${BANK_SERVICE_SERVICE_HOST}:${BANK_SERVICE_SERVICE_PORT}
kind: ConfigMap
metadata:
  name: api-gateway-config-map
---

# deployment config for user service
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 2
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: barathece91/user-service
        ports:
        - containerPort: 9001
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
              configMapKeyRef:
                  name: spring-config-map
                  key: spring.profiles.active
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "user-service"
        from:
          kind: "ImageStreamTag"
          name: "barathece91/user-service:latest" 
  strategy: 
    type: "Rolling"

---

# deployment config for bank service
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: bank-app
spec:
  selector:
    matchLabels:
      app: bank-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:   
      - name: bank-service
        image: barathece91/bank-service
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
              configMapKeyRef:
                  name: spring-config-map
                  key: spring.profiles.active
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "bank-service"
        from:
          kind: "ImageStreamTag"
          name: "barathece91/bank-service:latest" 
  strategy: 
    type: "Rolling"
---


# deployment config for api gateway

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: fork-join-api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: barathece91/fork-join-api-gateway
        ports:
        - containerPort: 9500
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
              configMapKeyRef:
                  name: spring-config-map
                  key: spring.profiles.active
        - name: user.service.url
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: user.service.url
        - name: bank.service.url
          valueFrom:
              configMapKeyRef:
                  name: api-gateway-config-map
                  key: bank.service.url
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "api-gateway"
        from:
          kind: "ImageStreamTag"
          name: "barathece91/fork-join-api-gateway:latest" 
  strategy: 
    type: "Rolling"
---


# deployment config for fork-join-demo ui

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: fork-join-demo-app
spec:
  selector:
    matchLabels:
      app: fork-join-demo-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: fork-join-demo-ui
    spec:
      containers:
      - name: fork-join-demo-ui
        image: barathece91/fork-join-demo-ui
        ports:
        - containerPort: 80
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "fork-join-demo-ui"
        from:
          kind: "ImageStreamTag"
          name: "barathece91/fork-join-demo-ui:latest" 
  strategy: 
    type: "Rolling"
---
kind: Service
apiVersion: v1
metadata:
  name: fork-join-api-gateway
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9500
    targetPort: 9500
---
kind: Service
apiVersion: v1
metadata:
  name: bank-service
spec:
  selector:
    app: bank-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
---
kind: Service
apiVersion: v1
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000


---
kind: Service
apiVersion: v1
metadata:
  name: fork-join-ui
spec:
  selector:
    app: fork-join-demo-ui
  type: NodePort
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 80
