platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: master
run:
  path: sh
  args:
            - -exec
            - |
                cd master/bank-service
                mvn clean install -DskipTests
caches:
  - path: /root/.m2
